
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const KnowledgeDocumentType = {
  PDF: 'PDF',
  DOCX: 'DOCX',
  PPTX: 'PPTX',
  TEXT: 'TEXT'
} as const

export type KnowledgeDocumentType = (typeof KnowledgeDocumentType)[keyof typeof KnowledgeDocumentType]


export const KnowledgeDocumentStatus = {
  QUEUED: 'QUEUED',
  PROCESSING: 'PROCESSING',
  READY: 'READY',
  FAILED: 'FAILED'
} as const

export type KnowledgeDocumentStatus = (typeof KnowledgeDocumentStatus)[keyof typeof KnowledgeDocumentStatus]


export const TextbookStatus = {
  QUEUED: 'QUEUED',
  OUTLINING: 'OUTLINING',
  READY: 'READY',
  FAILED_OUTLINING: 'FAILED_OUTLINING'
} as const

export type TextbookStatus = (typeof TextbookStatus)[keyof typeof TextbookStatus]


export const SectionStatus = {
  QUEUED: 'QUEUED',
  WRITING: 'WRITING',
  READY: 'READY',
  FAILED_WRITING: 'FAILED_WRITING',
  FAILED_REFINING: 'FAILED_REFINING'
} as const

export type SectionStatus = (typeof SectionStatus)[keyof typeof SectionStatus]
