
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const KnowledgeDocumentType = {
  PDF: 'PDF',
  DOCX: 'DOCX',
  PPTX: 'PPTX',
  TEXT: 'TEXT'
} as const

export type KnowledgeDocumentType = (typeof KnowledgeDocumentType)[keyof typeof KnowledgeDocumentType]


export const KnowledgeDocumentStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  READY: 'READY',
  FAILED: 'FAILED'
} as const

export type KnowledgeDocumentStatus = (typeof KnowledgeDocumentStatus)[keyof typeof KnowledgeDocumentStatus]
