
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `KnowledgeDocumentChunk` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model KnowledgeDocumentChunk
 * 
 */
export type KnowledgeDocumentChunkModel = runtime.Types.Result.DefaultSelection<Prisma.$KnowledgeDocumentChunkPayload>

export type AggregateKnowledgeDocumentChunk = {
  _count: KnowledgeDocumentChunkCountAggregateOutputType | null
  _avg: KnowledgeDocumentChunkAvgAggregateOutputType | null
  _sum: KnowledgeDocumentChunkSumAggregateOutputType | null
  _min: KnowledgeDocumentChunkMinAggregateOutputType | null
  _max: KnowledgeDocumentChunkMaxAggregateOutputType | null
}

export type KnowledgeDocumentChunkAvgAggregateOutputType = {
  index: number | null
}

export type KnowledgeDocumentChunkSumAggregateOutputType = {
  index: number | null
}

export type KnowledgeDocumentChunkMinAggregateOutputType = {
  id: string | null
  documentId: string | null
  index: number | null
  text: string | null
  createdAt: Date | null
}

export type KnowledgeDocumentChunkMaxAggregateOutputType = {
  id: string | null
  documentId: string | null
  index: number | null
  text: string | null
  createdAt: Date | null
}

export type KnowledgeDocumentChunkCountAggregateOutputType = {
  id: number
  documentId: number
  index: number
  text: number
  createdAt: number
  _all: number
}


export type KnowledgeDocumentChunkAvgAggregateInputType = {
  index?: true
}

export type KnowledgeDocumentChunkSumAggregateInputType = {
  index?: true
}

export type KnowledgeDocumentChunkMinAggregateInputType = {
  id?: true
  documentId?: true
  index?: true
  text?: true
  createdAt?: true
}

export type KnowledgeDocumentChunkMaxAggregateInputType = {
  id?: true
  documentId?: true
  index?: true
  text?: true
  createdAt?: true
}

export type KnowledgeDocumentChunkCountAggregateInputType = {
  id?: true
  documentId?: true
  index?: true
  text?: true
  createdAt?: true
  _all?: true
}

export type KnowledgeDocumentChunkAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which KnowledgeDocumentChunk to aggregate.
   */
  where?: Prisma.KnowledgeDocumentChunkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KnowledgeDocumentChunks to fetch.
   */
  orderBy?: Prisma.KnowledgeDocumentChunkOrderByWithRelationInput | Prisma.KnowledgeDocumentChunkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.KnowledgeDocumentChunkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KnowledgeDocumentChunks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KnowledgeDocumentChunks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned KnowledgeDocumentChunks
  **/
  _count?: true | KnowledgeDocumentChunkCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: KnowledgeDocumentChunkAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: KnowledgeDocumentChunkSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: KnowledgeDocumentChunkMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: KnowledgeDocumentChunkMaxAggregateInputType
}

export type GetKnowledgeDocumentChunkAggregateType<T extends KnowledgeDocumentChunkAggregateArgs> = {
      [P in keyof T & keyof AggregateKnowledgeDocumentChunk]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateKnowledgeDocumentChunk[P]>
    : Prisma.GetScalarType<T[P], AggregateKnowledgeDocumentChunk[P]>
}




export type KnowledgeDocumentChunkGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.KnowledgeDocumentChunkWhereInput
  orderBy?: Prisma.KnowledgeDocumentChunkOrderByWithAggregationInput | Prisma.KnowledgeDocumentChunkOrderByWithAggregationInput[]
  by: Prisma.KnowledgeDocumentChunkScalarFieldEnum[] | Prisma.KnowledgeDocumentChunkScalarFieldEnum
  having?: Prisma.KnowledgeDocumentChunkScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: KnowledgeDocumentChunkCountAggregateInputType | true
  _avg?: KnowledgeDocumentChunkAvgAggregateInputType
  _sum?: KnowledgeDocumentChunkSumAggregateInputType
  _min?: KnowledgeDocumentChunkMinAggregateInputType
  _max?: KnowledgeDocumentChunkMaxAggregateInputType
}

export type KnowledgeDocumentChunkGroupByOutputType = {
  id: string
  documentId: string
  index: number
  text: string
  createdAt: Date
  _count: KnowledgeDocumentChunkCountAggregateOutputType | null
  _avg: KnowledgeDocumentChunkAvgAggregateOutputType | null
  _sum: KnowledgeDocumentChunkSumAggregateOutputType | null
  _min: KnowledgeDocumentChunkMinAggregateOutputType | null
  _max: KnowledgeDocumentChunkMaxAggregateOutputType | null
}

export type GetKnowledgeDocumentChunkGroupByPayload<T extends KnowledgeDocumentChunkGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<KnowledgeDocumentChunkGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof KnowledgeDocumentChunkGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], KnowledgeDocumentChunkGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], KnowledgeDocumentChunkGroupByOutputType[P]>
      }
    >
  >



export type KnowledgeDocumentChunkWhereInput = {
  AND?: Prisma.KnowledgeDocumentChunkWhereInput | Prisma.KnowledgeDocumentChunkWhereInput[]
  OR?: Prisma.KnowledgeDocumentChunkWhereInput[]
  NOT?: Prisma.KnowledgeDocumentChunkWhereInput | Prisma.KnowledgeDocumentChunkWhereInput[]
  id?: Prisma.StringFilter<"KnowledgeDocumentChunk"> | string
  documentId?: Prisma.StringFilter<"KnowledgeDocumentChunk"> | string
  index?: Prisma.IntFilter<"KnowledgeDocumentChunk"> | number
  text?: Prisma.StringFilter<"KnowledgeDocumentChunk"> | string
  createdAt?: Prisma.DateTimeFilter<"KnowledgeDocumentChunk"> | Date | string
  document?: Prisma.XOR<Prisma.KnowledgeDocumentScalarRelationFilter, Prisma.KnowledgeDocumentWhereInput>
}

export type KnowledgeDocumentChunkOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  documentId?: Prisma.SortOrder
  index?: Prisma.SortOrder
  text?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  document?: Prisma.KnowledgeDocumentOrderByWithRelationInput
}

export type KnowledgeDocumentChunkWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.KnowledgeDocumentChunkWhereInput | Prisma.KnowledgeDocumentChunkWhereInput[]
  OR?: Prisma.KnowledgeDocumentChunkWhereInput[]
  NOT?: Prisma.KnowledgeDocumentChunkWhereInput | Prisma.KnowledgeDocumentChunkWhereInput[]
  documentId?: Prisma.StringFilter<"KnowledgeDocumentChunk"> | string
  index?: Prisma.IntFilter<"KnowledgeDocumentChunk"> | number
  text?: Prisma.StringFilter<"KnowledgeDocumentChunk"> | string
  createdAt?: Prisma.DateTimeFilter<"KnowledgeDocumentChunk"> | Date | string
  document?: Prisma.XOR<Prisma.KnowledgeDocumentScalarRelationFilter, Prisma.KnowledgeDocumentWhereInput>
}, "id">

export type KnowledgeDocumentChunkOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  documentId?: Prisma.SortOrder
  index?: Prisma.SortOrder
  text?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.KnowledgeDocumentChunkCountOrderByAggregateInput
  _avg?: Prisma.KnowledgeDocumentChunkAvgOrderByAggregateInput
  _max?: Prisma.KnowledgeDocumentChunkMaxOrderByAggregateInput
  _min?: Prisma.KnowledgeDocumentChunkMinOrderByAggregateInput
  _sum?: Prisma.KnowledgeDocumentChunkSumOrderByAggregateInput
}

export type KnowledgeDocumentChunkScalarWhereWithAggregatesInput = {
  AND?: Prisma.KnowledgeDocumentChunkScalarWhereWithAggregatesInput | Prisma.KnowledgeDocumentChunkScalarWhereWithAggregatesInput[]
  OR?: Prisma.KnowledgeDocumentChunkScalarWhereWithAggregatesInput[]
  NOT?: Prisma.KnowledgeDocumentChunkScalarWhereWithAggregatesInput | Prisma.KnowledgeDocumentChunkScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"KnowledgeDocumentChunk"> | string
  documentId?: Prisma.StringWithAggregatesFilter<"KnowledgeDocumentChunk"> | string
  index?: Prisma.IntWithAggregatesFilter<"KnowledgeDocumentChunk"> | number
  text?: Prisma.StringWithAggregatesFilter<"KnowledgeDocumentChunk"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"KnowledgeDocumentChunk"> | Date | string
}

export type KnowledgeDocumentChunkUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.IntFieldUpdateOperationsInput | number
  text?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  document?: Prisma.KnowledgeDocumentUpdateOneRequiredWithoutChunksNestedInput
}

export type KnowledgeDocumentChunkUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  documentId?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.IntFieldUpdateOperationsInput | number
  text?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KnowledgeDocumentChunkUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.IntFieldUpdateOperationsInput | number
  text?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KnowledgeDocumentChunkUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  documentId?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.IntFieldUpdateOperationsInput | number
  text?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KnowledgeDocumentChunkListRelationFilter = {
  every?: Prisma.KnowledgeDocumentChunkWhereInput
  some?: Prisma.KnowledgeDocumentChunkWhereInput
  none?: Prisma.KnowledgeDocumentChunkWhereInput
}

export type KnowledgeDocumentChunkOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type KnowledgeDocumentChunkCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  documentId?: Prisma.SortOrder
  index?: Prisma.SortOrder
  text?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type KnowledgeDocumentChunkAvgOrderByAggregateInput = {
  index?: Prisma.SortOrder
}

export type KnowledgeDocumentChunkMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  documentId?: Prisma.SortOrder
  index?: Prisma.SortOrder
  text?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type KnowledgeDocumentChunkMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  documentId?: Prisma.SortOrder
  index?: Prisma.SortOrder
  text?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type KnowledgeDocumentChunkSumOrderByAggregateInput = {
  index?: Prisma.SortOrder
}

export type KnowledgeDocumentChunkCreateNestedManyWithoutDocumentInput = {
  connect?: Prisma.KnowledgeDocumentChunkWhereUniqueInput | Prisma.KnowledgeDocumentChunkWhereUniqueInput[]
}

export type KnowledgeDocumentChunkUncheckedCreateNestedManyWithoutDocumentInput = {
  connect?: Prisma.KnowledgeDocumentChunkWhereUniqueInput | Prisma.KnowledgeDocumentChunkWhereUniqueInput[]
}

export type KnowledgeDocumentChunkUpdateManyWithoutDocumentNestedInput = {
  set?: Prisma.KnowledgeDocumentChunkWhereUniqueInput | Prisma.KnowledgeDocumentChunkWhereUniqueInput[]
  disconnect?: Prisma.KnowledgeDocumentChunkWhereUniqueInput | Prisma.KnowledgeDocumentChunkWhereUniqueInput[]
  delete?: Prisma.KnowledgeDocumentChunkWhereUniqueInput | Prisma.KnowledgeDocumentChunkWhereUniqueInput[]
  connect?: Prisma.KnowledgeDocumentChunkWhereUniqueInput | Prisma.KnowledgeDocumentChunkWhereUniqueInput[]
  update?: Prisma.KnowledgeDocumentChunkUpdateWithWhereUniqueWithoutDocumentInput | Prisma.KnowledgeDocumentChunkUpdateWithWhereUniqueWithoutDocumentInput[]
  updateMany?: Prisma.KnowledgeDocumentChunkUpdateManyWithWhereWithoutDocumentInput | Prisma.KnowledgeDocumentChunkUpdateManyWithWhereWithoutDocumentInput[]
  deleteMany?: Prisma.KnowledgeDocumentChunkScalarWhereInput | Prisma.KnowledgeDocumentChunkScalarWhereInput[]
}

export type KnowledgeDocumentChunkUncheckedUpdateManyWithoutDocumentNestedInput = {
  set?: Prisma.KnowledgeDocumentChunkWhereUniqueInput | Prisma.KnowledgeDocumentChunkWhereUniqueInput[]
  disconnect?: Prisma.KnowledgeDocumentChunkWhereUniqueInput | Prisma.KnowledgeDocumentChunkWhereUniqueInput[]
  delete?: Prisma.KnowledgeDocumentChunkWhereUniqueInput | Prisma.KnowledgeDocumentChunkWhereUniqueInput[]
  connect?: Prisma.KnowledgeDocumentChunkWhereUniqueInput | Prisma.KnowledgeDocumentChunkWhereUniqueInput[]
  update?: Prisma.KnowledgeDocumentChunkUpdateWithWhereUniqueWithoutDocumentInput | Prisma.KnowledgeDocumentChunkUpdateWithWhereUniqueWithoutDocumentInput[]
  updateMany?: Prisma.KnowledgeDocumentChunkUpdateManyWithWhereWithoutDocumentInput | Prisma.KnowledgeDocumentChunkUpdateManyWithWhereWithoutDocumentInput[]
  deleteMany?: Prisma.KnowledgeDocumentChunkScalarWhereInput | Prisma.KnowledgeDocumentChunkScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type KnowledgeDocumentChunkUpdateWithWhereUniqueWithoutDocumentInput = {
  where: Prisma.KnowledgeDocumentChunkWhereUniqueInput
  data: Prisma.XOR<Prisma.KnowledgeDocumentChunkUpdateWithoutDocumentInput, Prisma.KnowledgeDocumentChunkUncheckedUpdateWithoutDocumentInput>
}

export type KnowledgeDocumentChunkUpdateManyWithWhereWithoutDocumentInput = {
  where: Prisma.KnowledgeDocumentChunkScalarWhereInput
  data: Prisma.XOR<Prisma.KnowledgeDocumentChunkUpdateManyMutationInput, Prisma.KnowledgeDocumentChunkUncheckedUpdateManyWithoutDocumentInput>
}

export type KnowledgeDocumentChunkScalarWhereInput = {
  AND?: Prisma.KnowledgeDocumentChunkScalarWhereInput | Prisma.KnowledgeDocumentChunkScalarWhereInput[]
  OR?: Prisma.KnowledgeDocumentChunkScalarWhereInput[]
  NOT?: Prisma.KnowledgeDocumentChunkScalarWhereInput | Prisma.KnowledgeDocumentChunkScalarWhereInput[]
  id?: Prisma.StringFilter<"KnowledgeDocumentChunk"> | string
  documentId?: Prisma.StringFilter<"KnowledgeDocumentChunk"> | string
  index?: Prisma.IntFilter<"KnowledgeDocumentChunk"> | number
  text?: Prisma.StringFilter<"KnowledgeDocumentChunk"> | string
  createdAt?: Prisma.DateTimeFilter<"KnowledgeDocumentChunk"> | Date | string
}

export type KnowledgeDocumentChunkUpdateWithoutDocumentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.IntFieldUpdateOperationsInput | number
  text?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KnowledgeDocumentChunkUncheckedUpdateWithoutDocumentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.IntFieldUpdateOperationsInput | number
  text?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KnowledgeDocumentChunkUncheckedUpdateManyWithoutDocumentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.IntFieldUpdateOperationsInput | number
  text?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type KnowledgeDocumentChunkSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  documentId?: boolean
  index?: boolean
  text?: boolean
  createdAt?: boolean
  document?: boolean | Prisma.KnowledgeDocumentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["knowledgeDocumentChunk"]>


export type KnowledgeDocumentChunkSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  documentId?: boolean
  index?: boolean
  text?: boolean
  createdAt?: boolean
  document?: boolean | Prisma.KnowledgeDocumentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["knowledgeDocumentChunk"]>

export type KnowledgeDocumentChunkSelectScalar = {
  id?: boolean
  documentId?: boolean
  index?: boolean
  text?: boolean
  createdAt?: boolean
}

export type KnowledgeDocumentChunkOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "documentId" | "index" | "text" | "createdAt", ExtArgs["result"]["knowledgeDocumentChunk"]>
export type KnowledgeDocumentChunkInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  document?: boolean | Prisma.KnowledgeDocumentDefaultArgs<ExtArgs>
}
export type KnowledgeDocumentChunkIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  document?: boolean | Prisma.KnowledgeDocumentDefaultArgs<ExtArgs>
}

export type $KnowledgeDocumentChunkPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "KnowledgeDocumentChunk"
  objects: {
    document: Prisma.$KnowledgeDocumentPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    documentId: string
    index: number
    text: string
    createdAt: Date
  }, ExtArgs["result"]["knowledgeDocumentChunk"]>
  composites: {}
}

export type KnowledgeDocumentChunkGetPayload<S extends boolean | null | undefined | KnowledgeDocumentChunkDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$KnowledgeDocumentChunkPayload, S>

export type KnowledgeDocumentChunkCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<KnowledgeDocumentChunkFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: KnowledgeDocumentChunkCountAggregateInputType | true
  }

export interface KnowledgeDocumentChunkDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['KnowledgeDocumentChunk'], meta: { name: 'KnowledgeDocumentChunk' } }
  /**
   * Find zero or one KnowledgeDocumentChunk that matches the filter.
   * @param {KnowledgeDocumentChunkFindUniqueArgs} args - Arguments to find a KnowledgeDocumentChunk
   * @example
   * // Get one KnowledgeDocumentChunk
   * const knowledgeDocumentChunk = await prisma.knowledgeDocumentChunk.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends KnowledgeDocumentChunkFindUniqueArgs>(args: Prisma.SelectSubset<T, KnowledgeDocumentChunkFindUniqueArgs<ExtArgs>>): Prisma.Prisma__KnowledgeDocumentChunkClient<runtime.Types.Result.GetResult<Prisma.$KnowledgeDocumentChunkPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one KnowledgeDocumentChunk that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {KnowledgeDocumentChunkFindUniqueOrThrowArgs} args - Arguments to find a KnowledgeDocumentChunk
   * @example
   * // Get one KnowledgeDocumentChunk
   * const knowledgeDocumentChunk = await prisma.knowledgeDocumentChunk.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends KnowledgeDocumentChunkFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, KnowledgeDocumentChunkFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__KnowledgeDocumentChunkClient<runtime.Types.Result.GetResult<Prisma.$KnowledgeDocumentChunkPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first KnowledgeDocumentChunk that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KnowledgeDocumentChunkFindFirstArgs} args - Arguments to find a KnowledgeDocumentChunk
   * @example
   * // Get one KnowledgeDocumentChunk
   * const knowledgeDocumentChunk = await prisma.knowledgeDocumentChunk.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends KnowledgeDocumentChunkFindFirstArgs>(args?: Prisma.SelectSubset<T, KnowledgeDocumentChunkFindFirstArgs<ExtArgs>>): Prisma.Prisma__KnowledgeDocumentChunkClient<runtime.Types.Result.GetResult<Prisma.$KnowledgeDocumentChunkPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first KnowledgeDocumentChunk that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KnowledgeDocumentChunkFindFirstOrThrowArgs} args - Arguments to find a KnowledgeDocumentChunk
   * @example
   * // Get one KnowledgeDocumentChunk
   * const knowledgeDocumentChunk = await prisma.knowledgeDocumentChunk.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends KnowledgeDocumentChunkFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, KnowledgeDocumentChunkFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__KnowledgeDocumentChunkClient<runtime.Types.Result.GetResult<Prisma.$KnowledgeDocumentChunkPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more KnowledgeDocumentChunks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KnowledgeDocumentChunkFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all KnowledgeDocumentChunks
   * const knowledgeDocumentChunks = await prisma.knowledgeDocumentChunk.findMany()
   * 
   * // Get first 10 KnowledgeDocumentChunks
   * const knowledgeDocumentChunks = await prisma.knowledgeDocumentChunk.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const knowledgeDocumentChunkWithIdOnly = await prisma.knowledgeDocumentChunk.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends KnowledgeDocumentChunkFindManyArgs>(args?: Prisma.SelectSubset<T, KnowledgeDocumentChunkFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KnowledgeDocumentChunkPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Delete a KnowledgeDocumentChunk.
   * @param {KnowledgeDocumentChunkDeleteArgs} args - Arguments to delete one KnowledgeDocumentChunk.
   * @example
   * // Delete one KnowledgeDocumentChunk
   * const KnowledgeDocumentChunk = await prisma.knowledgeDocumentChunk.delete({
   *   where: {
   *     // ... filter to delete one KnowledgeDocumentChunk
   *   }
   * })
   * 
   */
  delete<T extends KnowledgeDocumentChunkDeleteArgs>(args: Prisma.SelectSubset<T, KnowledgeDocumentChunkDeleteArgs<ExtArgs>>): Prisma.Prisma__KnowledgeDocumentChunkClient<runtime.Types.Result.GetResult<Prisma.$KnowledgeDocumentChunkPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one KnowledgeDocumentChunk.
   * @param {KnowledgeDocumentChunkUpdateArgs} args - Arguments to update one KnowledgeDocumentChunk.
   * @example
   * // Update one KnowledgeDocumentChunk
   * const knowledgeDocumentChunk = await prisma.knowledgeDocumentChunk.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends KnowledgeDocumentChunkUpdateArgs>(args: Prisma.SelectSubset<T, KnowledgeDocumentChunkUpdateArgs<ExtArgs>>): Prisma.Prisma__KnowledgeDocumentChunkClient<runtime.Types.Result.GetResult<Prisma.$KnowledgeDocumentChunkPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more KnowledgeDocumentChunks.
   * @param {KnowledgeDocumentChunkDeleteManyArgs} args - Arguments to filter KnowledgeDocumentChunks to delete.
   * @example
   * // Delete a few KnowledgeDocumentChunks
   * const { count } = await prisma.knowledgeDocumentChunk.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends KnowledgeDocumentChunkDeleteManyArgs>(args?: Prisma.SelectSubset<T, KnowledgeDocumentChunkDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more KnowledgeDocumentChunks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KnowledgeDocumentChunkUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many KnowledgeDocumentChunks
   * const knowledgeDocumentChunk = await prisma.knowledgeDocumentChunk.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends KnowledgeDocumentChunkUpdateManyArgs>(args: Prisma.SelectSubset<T, KnowledgeDocumentChunkUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more KnowledgeDocumentChunks and returns the data updated in the database.
   * @param {KnowledgeDocumentChunkUpdateManyAndReturnArgs} args - Arguments to update many KnowledgeDocumentChunks.
   * @example
   * // Update many KnowledgeDocumentChunks
   * const knowledgeDocumentChunk = await prisma.knowledgeDocumentChunk.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more KnowledgeDocumentChunks and only return the `id`
   * const knowledgeDocumentChunkWithIdOnly = await prisma.knowledgeDocumentChunk.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends KnowledgeDocumentChunkUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, KnowledgeDocumentChunkUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KnowledgeDocumentChunkPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>


  /**
   * Count the number of KnowledgeDocumentChunks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KnowledgeDocumentChunkCountArgs} args - Arguments to filter KnowledgeDocumentChunks to count.
   * @example
   * // Count the number of KnowledgeDocumentChunks
   * const count = await prisma.knowledgeDocumentChunk.count({
   *   where: {
   *     // ... the filter for the KnowledgeDocumentChunks we want to count
   *   }
   * })
  **/
  count<T extends KnowledgeDocumentChunkCountArgs>(
    args?: Prisma.Subset<T, KnowledgeDocumentChunkCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], KnowledgeDocumentChunkCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a KnowledgeDocumentChunk.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KnowledgeDocumentChunkAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends KnowledgeDocumentChunkAggregateArgs>(args: Prisma.Subset<T, KnowledgeDocumentChunkAggregateArgs>): Prisma.PrismaPromise<GetKnowledgeDocumentChunkAggregateType<T>>

  /**
   * Group by KnowledgeDocumentChunk.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KnowledgeDocumentChunkGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends KnowledgeDocumentChunkGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: KnowledgeDocumentChunkGroupByArgs['orderBy'] }
      : { orderBy?: KnowledgeDocumentChunkGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, KnowledgeDocumentChunkGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetKnowledgeDocumentChunkGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the KnowledgeDocumentChunk model
 */
readonly fields: KnowledgeDocumentChunkFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for KnowledgeDocumentChunk.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__KnowledgeDocumentChunkClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  document<T extends Prisma.KnowledgeDocumentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.KnowledgeDocumentDefaultArgs<ExtArgs>>): Prisma.Prisma__KnowledgeDocumentClient<runtime.Types.Result.GetResult<Prisma.$KnowledgeDocumentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the KnowledgeDocumentChunk model
 */
export interface KnowledgeDocumentChunkFieldRefs {
  readonly id: Prisma.FieldRef<"KnowledgeDocumentChunk", 'String'>
  readonly documentId: Prisma.FieldRef<"KnowledgeDocumentChunk", 'String'>
  readonly index: Prisma.FieldRef<"KnowledgeDocumentChunk", 'Int'>
  readonly text: Prisma.FieldRef<"KnowledgeDocumentChunk", 'String'>
  readonly createdAt: Prisma.FieldRef<"KnowledgeDocumentChunk", 'DateTime'>
}
    

// Custom InputTypes
/**
 * KnowledgeDocumentChunk findUnique
 */
export type KnowledgeDocumentChunkFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KnowledgeDocumentChunk
   */
  select?: Prisma.KnowledgeDocumentChunkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KnowledgeDocumentChunk
   */
  omit?: Prisma.KnowledgeDocumentChunkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KnowledgeDocumentChunkInclude<ExtArgs> | null
  /**
   * Filter, which KnowledgeDocumentChunk to fetch.
   */
  where: Prisma.KnowledgeDocumentChunkWhereUniqueInput
}

/**
 * KnowledgeDocumentChunk findUniqueOrThrow
 */
export type KnowledgeDocumentChunkFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KnowledgeDocumentChunk
   */
  select?: Prisma.KnowledgeDocumentChunkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KnowledgeDocumentChunk
   */
  omit?: Prisma.KnowledgeDocumentChunkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KnowledgeDocumentChunkInclude<ExtArgs> | null
  /**
   * Filter, which KnowledgeDocumentChunk to fetch.
   */
  where: Prisma.KnowledgeDocumentChunkWhereUniqueInput
}

/**
 * KnowledgeDocumentChunk findFirst
 */
export type KnowledgeDocumentChunkFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KnowledgeDocumentChunk
   */
  select?: Prisma.KnowledgeDocumentChunkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KnowledgeDocumentChunk
   */
  omit?: Prisma.KnowledgeDocumentChunkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KnowledgeDocumentChunkInclude<ExtArgs> | null
  /**
   * Filter, which KnowledgeDocumentChunk to fetch.
   */
  where?: Prisma.KnowledgeDocumentChunkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KnowledgeDocumentChunks to fetch.
   */
  orderBy?: Prisma.KnowledgeDocumentChunkOrderByWithRelationInput | Prisma.KnowledgeDocumentChunkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for KnowledgeDocumentChunks.
   */
  cursor?: Prisma.KnowledgeDocumentChunkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KnowledgeDocumentChunks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KnowledgeDocumentChunks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of KnowledgeDocumentChunks.
   */
  distinct?: Prisma.KnowledgeDocumentChunkScalarFieldEnum | Prisma.KnowledgeDocumentChunkScalarFieldEnum[]
}

/**
 * KnowledgeDocumentChunk findFirstOrThrow
 */
export type KnowledgeDocumentChunkFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KnowledgeDocumentChunk
   */
  select?: Prisma.KnowledgeDocumentChunkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KnowledgeDocumentChunk
   */
  omit?: Prisma.KnowledgeDocumentChunkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KnowledgeDocumentChunkInclude<ExtArgs> | null
  /**
   * Filter, which KnowledgeDocumentChunk to fetch.
   */
  where?: Prisma.KnowledgeDocumentChunkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KnowledgeDocumentChunks to fetch.
   */
  orderBy?: Prisma.KnowledgeDocumentChunkOrderByWithRelationInput | Prisma.KnowledgeDocumentChunkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for KnowledgeDocumentChunks.
   */
  cursor?: Prisma.KnowledgeDocumentChunkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KnowledgeDocumentChunks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KnowledgeDocumentChunks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of KnowledgeDocumentChunks.
   */
  distinct?: Prisma.KnowledgeDocumentChunkScalarFieldEnum | Prisma.KnowledgeDocumentChunkScalarFieldEnum[]
}

/**
 * KnowledgeDocumentChunk findMany
 */
export type KnowledgeDocumentChunkFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KnowledgeDocumentChunk
   */
  select?: Prisma.KnowledgeDocumentChunkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KnowledgeDocumentChunk
   */
  omit?: Prisma.KnowledgeDocumentChunkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KnowledgeDocumentChunkInclude<ExtArgs> | null
  /**
   * Filter, which KnowledgeDocumentChunks to fetch.
   */
  where?: Prisma.KnowledgeDocumentChunkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KnowledgeDocumentChunks to fetch.
   */
  orderBy?: Prisma.KnowledgeDocumentChunkOrderByWithRelationInput | Prisma.KnowledgeDocumentChunkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing KnowledgeDocumentChunks.
   */
  cursor?: Prisma.KnowledgeDocumentChunkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KnowledgeDocumentChunks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KnowledgeDocumentChunks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of KnowledgeDocumentChunks.
   */
  distinct?: Prisma.KnowledgeDocumentChunkScalarFieldEnum | Prisma.KnowledgeDocumentChunkScalarFieldEnum[]
}

/**
 * KnowledgeDocumentChunk update
 */
export type KnowledgeDocumentChunkUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KnowledgeDocumentChunk
   */
  select?: Prisma.KnowledgeDocumentChunkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KnowledgeDocumentChunk
   */
  omit?: Prisma.KnowledgeDocumentChunkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KnowledgeDocumentChunkInclude<ExtArgs> | null
  /**
   * The data needed to update a KnowledgeDocumentChunk.
   */
  data: Prisma.XOR<Prisma.KnowledgeDocumentChunkUpdateInput, Prisma.KnowledgeDocumentChunkUncheckedUpdateInput>
  /**
   * Choose, which KnowledgeDocumentChunk to update.
   */
  where: Prisma.KnowledgeDocumentChunkWhereUniqueInput
}

/**
 * KnowledgeDocumentChunk updateMany
 */
export type KnowledgeDocumentChunkUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update KnowledgeDocumentChunks.
   */
  data: Prisma.XOR<Prisma.KnowledgeDocumentChunkUpdateManyMutationInput, Prisma.KnowledgeDocumentChunkUncheckedUpdateManyInput>
  /**
   * Filter which KnowledgeDocumentChunks to update
   */
  where?: Prisma.KnowledgeDocumentChunkWhereInput
  /**
   * Limit how many KnowledgeDocumentChunks to update.
   */
  limit?: number
}

/**
 * KnowledgeDocumentChunk updateManyAndReturn
 */
export type KnowledgeDocumentChunkUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KnowledgeDocumentChunk
   */
  select?: Prisma.KnowledgeDocumentChunkSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the KnowledgeDocumentChunk
   */
  omit?: Prisma.KnowledgeDocumentChunkOmit<ExtArgs> | null
  /**
   * The data used to update KnowledgeDocumentChunks.
   */
  data: Prisma.XOR<Prisma.KnowledgeDocumentChunkUpdateManyMutationInput, Prisma.KnowledgeDocumentChunkUncheckedUpdateManyInput>
  /**
   * Filter which KnowledgeDocumentChunks to update
   */
  where?: Prisma.KnowledgeDocumentChunkWhereInput
  /**
   * Limit how many KnowledgeDocumentChunks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KnowledgeDocumentChunkIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * KnowledgeDocumentChunk delete
 */
export type KnowledgeDocumentChunkDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KnowledgeDocumentChunk
   */
  select?: Prisma.KnowledgeDocumentChunkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KnowledgeDocumentChunk
   */
  omit?: Prisma.KnowledgeDocumentChunkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KnowledgeDocumentChunkInclude<ExtArgs> | null
  /**
   * Filter which KnowledgeDocumentChunk to delete.
   */
  where: Prisma.KnowledgeDocumentChunkWhereUniqueInput
}

/**
 * KnowledgeDocumentChunk deleteMany
 */
export type KnowledgeDocumentChunkDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which KnowledgeDocumentChunks to delete
   */
  where?: Prisma.KnowledgeDocumentChunkWhereInput
  /**
   * Limit how many KnowledgeDocumentChunks to delete.
   */
  limit?: number
}

/**
 * KnowledgeDocumentChunk without action
 */
export type KnowledgeDocumentChunkDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KnowledgeDocumentChunk
   */
  select?: Prisma.KnowledgeDocumentChunkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KnowledgeDocumentChunk
   */
  omit?: Prisma.KnowledgeDocumentChunkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KnowledgeDocumentChunkInclude<ExtArgs> | null
}
