
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Textbook` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Textbook
 * 
 */
export type TextbookModel = runtime.Types.Result.DefaultSelection<Prisma.$TextbookPayload>

export type AggregateTextbook = {
  _count: TextbookCountAggregateOutputType | null
  _min: TextbookMinAggregateOutputType | null
  _max: TextbookMaxAggregateOutputType | null
}

export type TextbookMinAggregateOutputType = {
  id: string | null
  title: string | null
  authorId: string | null
  description: string | null
  class: string | null
  uploadKey: string | null
  status: $Enums.TextbookStatus | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TextbookMaxAggregateOutputType = {
  id: string | null
  title: string | null
  authorId: string | null
  description: string | null
  class: string | null
  uploadKey: string | null
  status: $Enums.TextbookStatus | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TextbookCountAggregateOutputType = {
  id: number
  title: number
  authorId: number
  description: number
  class: number
  uploadKey: number
  status: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TextbookMinAggregateInputType = {
  id?: true
  title?: true
  authorId?: true
  description?: true
  class?: true
  uploadKey?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type TextbookMaxAggregateInputType = {
  id?: true
  title?: true
  authorId?: true
  description?: true
  class?: true
  uploadKey?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type TextbookCountAggregateInputType = {
  id?: true
  title?: true
  authorId?: true
  description?: true
  class?: true
  uploadKey?: true
  status?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TextbookAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Textbook to aggregate.
   */
  where?: Prisma.TextbookWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Textbooks to fetch.
   */
  orderBy?: Prisma.TextbookOrderByWithRelationInput | Prisma.TextbookOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TextbookWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Textbooks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Textbooks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Textbooks
  **/
  _count?: true | TextbookCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TextbookMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TextbookMaxAggregateInputType
}

export type GetTextbookAggregateType<T extends TextbookAggregateArgs> = {
      [P in keyof T & keyof AggregateTextbook]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTextbook[P]>
    : Prisma.GetScalarType<T[P], AggregateTextbook[P]>
}




export type TextbookGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TextbookWhereInput
  orderBy?: Prisma.TextbookOrderByWithAggregationInput | Prisma.TextbookOrderByWithAggregationInput[]
  by: Prisma.TextbookScalarFieldEnum[] | Prisma.TextbookScalarFieldEnum
  having?: Prisma.TextbookScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TextbookCountAggregateInputType | true
  _min?: TextbookMinAggregateInputType
  _max?: TextbookMaxAggregateInputType
}

export type TextbookGroupByOutputType = {
  id: string
  title: string | null
  authorId: string
  description: string | null
  class: string
  uploadKey: string | null
  status: $Enums.TextbookStatus
  createdAt: Date
  updatedAt: Date
  _count: TextbookCountAggregateOutputType | null
  _min: TextbookMinAggregateOutputType | null
  _max: TextbookMaxAggregateOutputType | null
}

export type GetTextbookGroupByPayload<T extends TextbookGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TextbookGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TextbookGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TextbookGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TextbookGroupByOutputType[P]>
      }
    >
  >



export type TextbookWhereInput = {
  AND?: Prisma.TextbookWhereInput | Prisma.TextbookWhereInput[]
  OR?: Prisma.TextbookWhereInput[]
  NOT?: Prisma.TextbookWhereInput | Prisma.TextbookWhereInput[]
  id?: Prisma.StringFilter<"Textbook"> | string
  title?: Prisma.StringNullableFilter<"Textbook"> | string | null
  authorId?: Prisma.StringFilter<"Textbook"> | string
  description?: Prisma.StringNullableFilter<"Textbook"> | string | null
  class?: Prisma.StringFilter<"Textbook"> | string
  uploadKey?: Prisma.StringNullableFilter<"Textbook"> | string | null
  status?: Prisma.EnumTextbookStatusFilter<"Textbook"> | $Enums.TextbookStatus
  createdAt?: Prisma.DateTimeFilter<"Textbook"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Textbook"> | Date | string
  sources?: Prisma.KnowledgeDocumentListRelationFilter
  chapters?: Prisma.ChapterListRelationFilter
  author?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type TextbookOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrderInput | Prisma.SortOrder
  authorId?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  class?: Prisma.SortOrder
  uploadKey?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  sources?: Prisma.KnowledgeDocumentOrderByRelationAggregateInput
  chapters?: Prisma.ChapterOrderByRelationAggregateInput
  author?: Prisma.UserOrderByWithRelationInput
}

export type TextbookWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TextbookWhereInput | Prisma.TextbookWhereInput[]
  OR?: Prisma.TextbookWhereInput[]
  NOT?: Prisma.TextbookWhereInput | Prisma.TextbookWhereInput[]
  title?: Prisma.StringNullableFilter<"Textbook"> | string | null
  authorId?: Prisma.StringFilter<"Textbook"> | string
  description?: Prisma.StringNullableFilter<"Textbook"> | string | null
  class?: Prisma.StringFilter<"Textbook"> | string
  uploadKey?: Prisma.StringNullableFilter<"Textbook"> | string | null
  status?: Prisma.EnumTextbookStatusFilter<"Textbook"> | $Enums.TextbookStatus
  createdAt?: Prisma.DateTimeFilter<"Textbook"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Textbook"> | Date | string
  sources?: Prisma.KnowledgeDocumentListRelationFilter
  chapters?: Prisma.ChapterListRelationFilter
  author?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type TextbookOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrderInput | Prisma.SortOrder
  authorId?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  class?: Prisma.SortOrder
  uploadKey?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TextbookCountOrderByAggregateInput
  _max?: Prisma.TextbookMaxOrderByAggregateInput
  _min?: Prisma.TextbookMinOrderByAggregateInput
}

export type TextbookScalarWhereWithAggregatesInput = {
  AND?: Prisma.TextbookScalarWhereWithAggregatesInput | Prisma.TextbookScalarWhereWithAggregatesInput[]
  OR?: Prisma.TextbookScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TextbookScalarWhereWithAggregatesInput | Prisma.TextbookScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Textbook"> | string
  title?: Prisma.StringNullableWithAggregatesFilter<"Textbook"> | string | null
  authorId?: Prisma.StringWithAggregatesFilter<"Textbook"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"Textbook"> | string | null
  class?: Prisma.StringWithAggregatesFilter<"Textbook"> | string
  uploadKey?: Prisma.StringNullableWithAggregatesFilter<"Textbook"> | string | null
  status?: Prisma.EnumTextbookStatusWithAggregatesFilter<"Textbook"> | $Enums.TextbookStatus
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Textbook"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Textbook"> | Date | string
}

export type TextbookCreateInput = {
  id?: string
  title?: string | null
  description?: string | null
  class?: string
  uploadKey?: string | null
  status?: $Enums.TextbookStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  sources?: Prisma.KnowledgeDocumentCreateNestedManyWithoutReferencedInInput
  chapters?: Prisma.ChapterCreateNestedManyWithoutTextbookInput
  author: Prisma.UserCreateNestedOneWithoutTextbooksInput
}

export type TextbookUncheckedCreateInput = {
  id?: string
  title?: string | null
  authorId: string
  description?: string | null
  class?: string
  uploadKey?: string | null
  status?: $Enums.TextbookStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  sources?: Prisma.KnowledgeDocumentUncheckedCreateNestedManyWithoutReferencedInInput
  chapters?: Prisma.ChapterUncheckedCreateNestedManyWithoutTextbookInput
}

export type TextbookUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  class?: Prisma.StringFieldUpdateOperationsInput | string
  uploadKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTextbookStatusFieldUpdateOperationsInput | $Enums.TextbookStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sources?: Prisma.KnowledgeDocumentUpdateManyWithoutReferencedInNestedInput
  chapters?: Prisma.ChapterUpdateManyWithoutTextbookNestedInput
  author?: Prisma.UserUpdateOneRequiredWithoutTextbooksNestedInput
}

export type TextbookUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  class?: Prisma.StringFieldUpdateOperationsInput | string
  uploadKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTextbookStatusFieldUpdateOperationsInput | $Enums.TextbookStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sources?: Prisma.KnowledgeDocumentUncheckedUpdateManyWithoutReferencedInNestedInput
  chapters?: Prisma.ChapterUncheckedUpdateManyWithoutTextbookNestedInput
}

export type TextbookCreateManyInput = {
  id?: string
  title?: string | null
  authorId: string
  description?: string | null
  class?: string
  uploadKey?: string | null
  status?: $Enums.TextbookStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TextbookUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  class?: Prisma.StringFieldUpdateOperationsInput | string
  uploadKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTextbookStatusFieldUpdateOperationsInput | $Enums.TextbookStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TextbookUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  class?: Prisma.StringFieldUpdateOperationsInput | string
  uploadKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTextbookStatusFieldUpdateOperationsInput | $Enums.TextbookStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TextbookListRelationFilter = {
  every?: Prisma.TextbookWhereInput
  some?: Prisma.TextbookWhereInput
  none?: Prisma.TextbookWhereInput
}

export type TextbookOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TextbookCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  description?: Prisma.SortOrder
  class?: Prisma.SortOrder
  uploadKey?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TextbookMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  description?: Prisma.SortOrder
  class?: Prisma.SortOrder
  uploadKey?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TextbookMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  description?: Prisma.SortOrder
  class?: Prisma.SortOrder
  uploadKey?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TextbookScalarRelationFilter = {
  is?: Prisma.TextbookWhereInput
  isNot?: Prisma.TextbookWhereInput
}

export type TextbookCreateNestedManyWithoutAuthorInput = {
  create?: Prisma.XOR<Prisma.TextbookCreateWithoutAuthorInput, Prisma.TextbookUncheckedCreateWithoutAuthorInput> | Prisma.TextbookCreateWithoutAuthorInput[] | Prisma.TextbookUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.TextbookCreateOrConnectWithoutAuthorInput | Prisma.TextbookCreateOrConnectWithoutAuthorInput[]
  createMany?: Prisma.TextbookCreateManyAuthorInputEnvelope
  connect?: Prisma.TextbookWhereUniqueInput | Prisma.TextbookWhereUniqueInput[]
}

export type TextbookUncheckedCreateNestedManyWithoutAuthorInput = {
  create?: Prisma.XOR<Prisma.TextbookCreateWithoutAuthorInput, Prisma.TextbookUncheckedCreateWithoutAuthorInput> | Prisma.TextbookCreateWithoutAuthorInput[] | Prisma.TextbookUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.TextbookCreateOrConnectWithoutAuthorInput | Prisma.TextbookCreateOrConnectWithoutAuthorInput[]
  createMany?: Prisma.TextbookCreateManyAuthorInputEnvelope
  connect?: Prisma.TextbookWhereUniqueInput | Prisma.TextbookWhereUniqueInput[]
}

export type TextbookUpdateManyWithoutAuthorNestedInput = {
  create?: Prisma.XOR<Prisma.TextbookCreateWithoutAuthorInput, Prisma.TextbookUncheckedCreateWithoutAuthorInput> | Prisma.TextbookCreateWithoutAuthorInput[] | Prisma.TextbookUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.TextbookCreateOrConnectWithoutAuthorInput | Prisma.TextbookCreateOrConnectWithoutAuthorInput[]
  upsert?: Prisma.TextbookUpsertWithWhereUniqueWithoutAuthorInput | Prisma.TextbookUpsertWithWhereUniqueWithoutAuthorInput[]
  createMany?: Prisma.TextbookCreateManyAuthorInputEnvelope
  set?: Prisma.TextbookWhereUniqueInput | Prisma.TextbookWhereUniqueInput[]
  disconnect?: Prisma.TextbookWhereUniqueInput | Prisma.TextbookWhereUniqueInput[]
  delete?: Prisma.TextbookWhereUniqueInput | Prisma.TextbookWhereUniqueInput[]
  connect?: Prisma.TextbookWhereUniqueInput | Prisma.TextbookWhereUniqueInput[]
  update?: Prisma.TextbookUpdateWithWhereUniqueWithoutAuthorInput | Prisma.TextbookUpdateWithWhereUniqueWithoutAuthorInput[]
  updateMany?: Prisma.TextbookUpdateManyWithWhereWithoutAuthorInput | Prisma.TextbookUpdateManyWithWhereWithoutAuthorInput[]
  deleteMany?: Prisma.TextbookScalarWhereInput | Prisma.TextbookScalarWhereInput[]
}

export type TextbookUncheckedUpdateManyWithoutAuthorNestedInput = {
  create?: Prisma.XOR<Prisma.TextbookCreateWithoutAuthorInput, Prisma.TextbookUncheckedCreateWithoutAuthorInput> | Prisma.TextbookCreateWithoutAuthorInput[] | Prisma.TextbookUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.TextbookCreateOrConnectWithoutAuthorInput | Prisma.TextbookCreateOrConnectWithoutAuthorInput[]
  upsert?: Prisma.TextbookUpsertWithWhereUniqueWithoutAuthorInput | Prisma.TextbookUpsertWithWhereUniqueWithoutAuthorInput[]
  createMany?: Prisma.TextbookCreateManyAuthorInputEnvelope
  set?: Prisma.TextbookWhereUniqueInput | Prisma.TextbookWhereUniqueInput[]
  disconnect?: Prisma.TextbookWhereUniqueInput | Prisma.TextbookWhereUniqueInput[]
  delete?: Prisma.TextbookWhereUniqueInput | Prisma.TextbookWhereUniqueInput[]
  connect?: Prisma.TextbookWhereUniqueInput | Prisma.TextbookWhereUniqueInput[]
  update?: Prisma.TextbookUpdateWithWhereUniqueWithoutAuthorInput | Prisma.TextbookUpdateWithWhereUniqueWithoutAuthorInput[]
  updateMany?: Prisma.TextbookUpdateManyWithWhereWithoutAuthorInput | Prisma.TextbookUpdateManyWithWhereWithoutAuthorInput[]
  deleteMany?: Prisma.TextbookScalarWhereInput | Prisma.TextbookScalarWhereInput[]
}

export type TextbookCreateNestedManyWithoutSourcesInput = {
  create?: Prisma.XOR<Prisma.TextbookCreateWithoutSourcesInput, Prisma.TextbookUncheckedCreateWithoutSourcesInput> | Prisma.TextbookCreateWithoutSourcesInput[] | Prisma.TextbookUncheckedCreateWithoutSourcesInput[]
  connectOrCreate?: Prisma.TextbookCreateOrConnectWithoutSourcesInput | Prisma.TextbookCreateOrConnectWithoutSourcesInput[]
  connect?: Prisma.TextbookWhereUniqueInput | Prisma.TextbookWhereUniqueInput[]
}

export type TextbookUncheckedCreateNestedManyWithoutSourcesInput = {
  create?: Prisma.XOR<Prisma.TextbookCreateWithoutSourcesInput, Prisma.TextbookUncheckedCreateWithoutSourcesInput> | Prisma.TextbookCreateWithoutSourcesInput[] | Prisma.TextbookUncheckedCreateWithoutSourcesInput[]
  connectOrCreate?: Prisma.TextbookCreateOrConnectWithoutSourcesInput | Prisma.TextbookCreateOrConnectWithoutSourcesInput[]
  connect?: Prisma.TextbookWhereUniqueInput | Prisma.TextbookWhereUniqueInput[]
}

export type TextbookUpdateManyWithoutSourcesNestedInput = {
  create?: Prisma.XOR<Prisma.TextbookCreateWithoutSourcesInput, Prisma.TextbookUncheckedCreateWithoutSourcesInput> | Prisma.TextbookCreateWithoutSourcesInput[] | Prisma.TextbookUncheckedCreateWithoutSourcesInput[]
  connectOrCreate?: Prisma.TextbookCreateOrConnectWithoutSourcesInput | Prisma.TextbookCreateOrConnectWithoutSourcesInput[]
  upsert?: Prisma.TextbookUpsertWithWhereUniqueWithoutSourcesInput | Prisma.TextbookUpsertWithWhereUniqueWithoutSourcesInput[]
  set?: Prisma.TextbookWhereUniqueInput | Prisma.TextbookWhereUniqueInput[]
  disconnect?: Prisma.TextbookWhereUniqueInput | Prisma.TextbookWhereUniqueInput[]
  delete?: Prisma.TextbookWhereUniqueInput | Prisma.TextbookWhereUniqueInput[]
  connect?: Prisma.TextbookWhereUniqueInput | Prisma.TextbookWhereUniqueInput[]
  update?: Prisma.TextbookUpdateWithWhereUniqueWithoutSourcesInput | Prisma.TextbookUpdateWithWhereUniqueWithoutSourcesInput[]
  updateMany?: Prisma.TextbookUpdateManyWithWhereWithoutSourcesInput | Prisma.TextbookUpdateManyWithWhereWithoutSourcesInput[]
  deleteMany?: Prisma.TextbookScalarWhereInput | Prisma.TextbookScalarWhereInput[]
}

export type TextbookUncheckedUpdateManyWithoutSourcesNestedInput = {
  create?: Prisma.XOR<Prisma.TextbookCreateWithoutSourcesInput, Prisma.TextbookUncheckedCreateWithoutSourcesInput> | Prisma.TextbookCreateWithoutSourcesInput[] | Prisma.TextbookUncheckedCreateWithoutSourcesInput[]
  connectOrCreate?: Prisma.TextbookCreateOrConnectWithoutSourcesInput | Prisma.TextbookCreateOrConnectWithoutSourcesInput[]
  upsert?: Prisma.TextbookUpsertWithWhereUniqueWithoutSourcesInput | Prisma.TextbookUpsertWithWhereUniqueWithoutSourcesInput[]
  set?: Prisma.TextbookWhereUniqueInput | Prisma.TextbookWhereUniqueInput[]
  disconnect?: Prisma.TextbookWhereUniqueInput | Prisma.TextbookWhereUniqueInput[]
  delete?: Prisma.TextbookWhereUniqueInput | Prisma.TextbookWhereUniqueInput[]
  connect?: Prisma.TextbookWhereUniqueInput | Prisma.TextbookWhereUniqueInput[]
  update?: Prisma.TextbookUpdateWithWhereUniqueWithoutSourcesInput | Prisma.TextbookUpdateWithWhereUniqueWithoutSourcesInput[]
  updateMany?: Prisma.TextbookUpdateManyWithWhereWithoutSourcesInput | Prisma.TextbookUpdateManyWithWhereWithoutSourcesInput[]
  deleteMany?: Prisma.TextbookScalarWhereInput | Prisma.TextbookScalarWhereInput[]
}

export type EnumTextbookStatusFieldUpdateOperationsInput = {
  set?: $Enums.TextbookStatus
}

export type TextbookCreateNestedOneWithoutChaptersInput = {
  create?: Prisma.XOR<Prisma.TextbookCreateWithoutChaptersInput, Prisma.TextbookUncheckedCreateWithoutChaptersInput>
  connectOrCreate?: Prisma.TextbookCreateOrConnectWithoutChaptersInput
  connect?: Prisma.TextbookWhereUniqueInput
}

export type TextbookUpdateOneRequiredWithoutChaptersNestedInput = {
  create?: Prisma.XOR<Prisma.TextbookCreateWithoutChaptersInput, Prisma.TextbookUncheckedCreateWithoutChaptersInput>
  connectOrCreate?: Prisma.TextbookCreateOrConnectWithoutChaptersInput
  upsert?: Prisma.TextbookUpsertWithoutChaptersInput
  connect?: Prisma.TextbookWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TextbookUpdateToOneWithWhereWithoutChaptersInput, Prisma.TextbookUpdateWithoutChaptersInput>, Prisma.TextbookUncheckedUpdateWithoutChaptersInput>
}

export type TextbookCreateWithoutAuthorInput = {
  id?: string
  title?: string | null
  description?: string | null
  class?: string
  uploadKey?: string | null
  status?: $Enums.TextbookStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  sources?: Prisma.KnowledgeDocumentCreateNestedManyWithoutReferencedInInput
  chapters?: Prisma.ChapterCreateNestedManyWithoutTextbookInput
}

export type TextbookUncheckedCreateWithoutAuthorInput = {
  id?: string
  title?: string | null
  description?: string | null
  class?: string
  uploadKey?: string | null
  status?: $Enums.TextbookStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  sources?: Prisma.KnowledgeDocumentUncheckedCreateNestedManyWithoutReferencedInInput
  chapters?: Prisma.ChapterUncheckedCreateNestedManyWithoutTextbookInput
}

export type TextbookCreateOrConnectWithoutAuthorInput = {
  where: Prisma.TextbookWhereUniqueInput
  create: Prisma.XOR<Prisma.TextbookCreateWithoutAuthorInput, Prisma.TextbookUncheckedCreateWithoutAuthorInput>
}

export type TextbookCreateManyAuthorInputEnvelope = {
  data: Prisma.TextbookCreateManyAuthorInput | Prisma.TextbookCreateManyAuthorInput[]
  skipDuplicates?: boolean
}

export type TextbookUpsertWithWhereUniqueWithoutAuthorInput = {
  where: Prisma.TextbookWhereUniqueInput
  update: Prisma.XOR<Prisma.TextbookUpdateWithoutAuthorInput, Prisma.TextbookUncheckedUpdateWithoutAuthorInput>
  create: Prisma.XOR<Prisma.TextbookCreateWithoutAuthorInput, Prisma.TextbookUncheckedCreateWithoutAuthorInput>
}

export type TextbookUpdateWithWhereUniqueWithoutAuthorInput = {
  where: Prisma.TextbookWhereUniqueInput
  data: Prisma.XOR<Prisma.TextbookUpdateWithoutAuthorInput, Prisma.TextbookUncheckedUpdateWithoutAuthorInput>
}

export type TextbookUpdateManyWithWhereWithoutAuthorInput = {
  where: Prisma.TextbookScalarWhereInput
  data: Prisma.XOR<Prisma.TextbookUpdateManyMutationInput, Prisma.TextbookUncheckedUpdateManyWithoutAuthorInput>
}

export type TextbookScalarWhereInput = {
  AND?: Prisma.TextbookScalarWhereInput | Prisma.TextbookScalarWhereInput[]
  OR?: Prisma.TextbookScalarWhereInput[]
  NOT?: Prisma.TextbookScalarWhereInput | Prisma.TextbookScalarWhereInput[]
  id?: Prisma.StringFilter<"Textbook"> | string
  title?: Prisma.StringNullableFilter<"Textbook"> | string | null
  authorId?: Prisma.StringFilter<"Textbook"> | string
  description?: Prisma.StringNullableFilter<"Textbook"> | string | null
  class?: Prisma.StringFilter<"Textbook"> | string
  uploadKey?: Prisma.StringNullableFilter<"Textbook"> | string | null
  status?: Prisma.EnumTextbookStatusFilter<"Textbook"> | $Enums.TextbookStatus
  createdAt?: Prisma.DateTimeFilter<"Textbook"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Textbook"> | Date | string
}

export type TextbookCreateWithoutSourcesInput = {
  id?: string
  title?: string | null
  description?: string | null
  class?: string
  uploadKey?: string | null
  status?: $Enums.TextbookStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  chapters?: Prisma.ChapterCreateNestedManyWithoutTextbookInput
  author: Prisma.UserCreateNestedOneWithoutTextbooksInput
}

export type TextbookUncheckedCreateWithoutSourcesInput = {
  id?: string
  title?: string | null
  authorId: string
  description?: string | null
  class?: string
  uploadKey?: string | null
  status?: $Enums.TextbookStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  chapters?: Prisma.ChapterUncheckedCreateNestedManyWithoutTextbookInput
}

export type TextbookCreateOrConnectWithoutSourcesInput = {
  where: Prisma.TextbookWhereUniqueInput
  create: Prisma.XOR<Prisma.TextbookCreateWithoutSourcesInput, Prisma.TextbookUncheckedCreateWithoutSourcesInput>
}

export type TextbookUpsertWithWhereUniqueWithoutSourcesInput = {
  where: Prisma.TextbookWhereUniqueInput
  update: Prisma.XOR<Prisma.TextbookUpdateWithoutSourcesInput, Prisma.TextbookUncheckedUpdateWithoutSourcesInput>
  create: Prisma.XOR<Prisma.TextbookCreateWithoutSourcesInput, Prisma.TextbookUncheckedCreateWithoutSourcesInput>
}

export type TextbookUpdateWithWhereUniqueWithoutSourcesInput = {
  where: Prisma.TextbookWhereUniqueInput
  data: Prisma.XOR<Prisma.TextbookUpdateWithoutSourcesInput, Prisma.TextbookUncheckedUpdateWithoutSourcesInput>
}

export type TextbookUpdateManyWithWhereWithoutSourcesInput = {
  where: Prisma.TextbookScalarWhereInput
  data: Prisma.XOR<Prisma.TextbookUpdateManyMutationInput, Prisma.TextbookUncheckedUpdateManyWithoutSourcesInput>
}

export type TextbookCreateWithoutChaptersInput = {
  id?: string
  title?: string | null
  description?: string | null
  class?: string
  uploadKey?: string | null
  status?: $Enums.TextbookStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  sources?: Prisma.KnowledgeDocumentCreateNestedManyWithoutReferencedInInput
  author: Prisma.UserCreateNestedOneWithoutTextbooksInput
}

export type TextbookUncheckedCreateWithoutChaptersInput = {
  id?: string
  title?: string | null
  authorId: string
  description?: string | null
  class?: string
  uploadKey?: string | null
  status?: $Enums.TextbookStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  sources?: Prisma.KnowledgeDocumentUncheckedCreateNestedManyWithoutReferencedInInput
}

export type TextbookCreateOrConnectWithoutChaptersInput = {
  where: Prisma.TextbookWhereUniqueInput
  create: Prisma.XOR<Prisma.TextbookCreateWithoutChaptersInput, Prisma.TextbookUncheckedCreateWithoutChaptersInput>
}

export type TextbookUpsertWithoutChaptersInput = {
  update: Prisma.XOR<Prisma.TextbookUpdateWithoutChaptersInput, Prisma.TextbookUncheckedUpdateWithoutChaptersInput>
  create: Prisma.XOR<Prisma.TextbookCreateWithoutChaptersInput, Prisma.TextbookUncheckedCreateWithoutChaptersInput>
  where?: Prisma.TextbookWhereInput
}

export type TextbookUpdateToOneWithWhereWithoutChaptersInput = {
  where?: Prisma.TextbookWhereInput
  data: Prisma.XOR<Prisma.TextbookUpdateWithoutChaptersInput, Prisma.TextbookUncheckedUpdateWithoutChaptersInput>
}

export type TextbookUpdateWithoutChaptersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  class?: Prisma.StringFieldUpdateOperationsInput | string
  uploadKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTextbookStatusFieldUpdateOperationsInput | $Enums.TextbookStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sources?: Prisma.KnowledgeDocumentUpdateManyWithoutReferencedInNestedInput
  author?: Prisma.UserUpdateOneRequiredWithoutTextbooksNestedInput
}

export type TextbookUncheckedUpdateWithoutChaptersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  class?: Prisma.StringFieldUpdateOperationsInput | string
  uploadKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTextbookStatusFieldUpdateOperationsInput | $Enums.TextbookStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sources?: Prisma.KnowledgeDocumentUncheckedUpdateManyWithoutReferencedInNestedInput
}

export type TextbookCreateManyAuthorInput = {
  id?: string
  title?: string | null
  description?: string | null
  class?: string
  uploadKey?: string | null
  status?: $Enums.TextbookStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TextbookUpdateWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  class?: Prisma.StringFieldUpdateOperationsInput | string
  uploadKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTextbookStatusFieldUpdateOperationsInput | $Enums.TextbookStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sources?: Prisma.KnowledgeDocumentUpdateManyWithoutReferencedInNestedInput
  chapters?: Prisma.ChapterUpdateManyWithoutTextbookNestedInput
}

export type TextbookUncheckedUpdateWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  class?: Prisma.StringFieldUpdateOperationsInput | string
  uploadKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTextbookStatusFieldUpdateOperationsInput | $Enums.TextbookStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sources?: Prisma.KnowledgeDocumentUncheckedUpdateManyWithoutReferencedInNestedInput
  chapters?: Prisma.ChapterUncheckedUpdateManyWithoutTextbookNestedInput
}

export type TextbookUncheckedUpdateManyWithoutAuthorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  class?: Prisma.StringFieldUpdateOperationsInput | string
  uploadKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTextbookStatusFieldUpdateOperationsInput | $Enums.TextbookStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TextbookUpdateWithoutSourcesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  class?: Prisma.StringFieldUpdateOperationsInput | string
  uploadKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTextbookStatusFieldUpdateOperationsInput | $Enums.TextbookStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chapters?: Prisma.ChapterUpdateManyWithoutTextbookNestedInput
  author?: Prisma.UserUpdateOneRequiredWithoutTextbooksNestedInput
}

export type TextbookUncheckedUpdateWithoutSourcesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  class?: Prisma.StringFieldUpdateOperationsInput | string
  uploadKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTextbookStatusFieldUpdateOperationsInput | $Enums.TextbookStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chapters?: Prisma.ChapterUncheckedUpdateManyWithoutTextbookNestedInput
}

export type TextbookUncheckedUpdateManyWithoutSourcesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  class?: Prisma.StringFieldUpdateOperationsInput | string
  uploadKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTextbookStatusFieldUpdateOperationsInput | $Enums.TextbookStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type TextbookCountOutputType
 */

export type TextbookCountOutputType = {
  sources: number
  chapters: number
}

export type TextbookCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sources?: boolean | TextbookCountOutputTypeCountSourcesArgs
  chapters?: boolean | TextbookCountOutputTypeCountChaptersArgs
}

/**
 * TextbookCountOutputType without action
 */
export type TextbookCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TextbookCountOutputType
   */
  select?: Prisma.TextbookCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TextbookCountOutputType without action
 */
export type TextbookCountOutputTypeCountSourcesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.KnowledgeDocumentWhereInput
}

/**
 * TextbookCountOutputType without action
 */
export type TextbookCountOutputTypeCountChaptersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ChapterWhereInput
}


export type TextbookSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  authorId?: boolean
  description?: boolean
  class?: boolean
  uploadKey?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  sources?: boolean | Prisma.Textbook$sourcesArgs<ExtArgs>
  chapters?: boolean | Prisma.Textbook$chaptersArgs<ExtArgs>
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.TextbookCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["textbook"]>

export type TextbookSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  authorId?: boolean
  description?: boolean
  class?: boolean
  uploadKey?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["textbook"]>

export type TextbookSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  authorId?: boolean
  description?: boolean
  class?: boolean
  uploadKey?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["textbook"]>

export type TextbookSelectScalar = {
  id?: boolean
  title?: boolean
  authorId?: boolean
  description?: boolean
  class?: boolean
  uploadKey?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TextbookOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "authorId" | "description" | "class" | "uploadKey" | "status" | "createdAt" | "updatedAt", ExtArgs["result"]["textbook"]>
export type TextbookInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sources?: boolean | Prisma.Textbook$sourcesArgs<ExtArgs>
  chapters?: boolean | Prisma.Textbook$chaptersArgs<ExtArgs>
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.TextbookCountOutputTypeDefaultArgs<ExtArgs>
}
export type TextbookIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type TextbookIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $TextbookPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Textbook"
  objects: {
    sources: Prisma.$KnowledgeDocumentPayload<ExtArgs>[]
    chapters: Prisma.$ChapterPayload<ExtArgs>[]
    author: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string | null
    authorId: string
    description: string | null
    class: string
    uploadKey: string | null
    status: $Enums.TextbookStatus
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["textbook"]>
  composites: {}
}

export type TextbookGetPayload<S extends boolean | null | undefined | TextbookDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TextbookPayload, S>

export type TextbookCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TextbookFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TextbookCountAggregateInputType | true
  }

export interface TextbookDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Textbook'], meta: { name: 'Textbook' } }
  /**
   * Find zero or one Textbook that matches the filter.
   * @param {TextbookFindUniqueArgs} args - Arguments to find a Textbook
   * @example
   * // Get one Textbook
   * const textbook = await prisma.textbook.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TextbookFindUniqueArgs>(args: Prisma.SelectSubset<T, TextbookFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TextbookClient<runtime.Types.Result.GetResult<Prisma.$TextbookPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Textbook that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TextbookFindUniqueOrThrowArgs} args - Arguments to find a Textbook
   * @example
   * // Get one Textbook
   * const textbook = await prisma.textbook.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TextbookFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TextbookFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TextbookClient<runtime.Types.Result.GetResult<Prisma.$TextbookPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Textbook that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TextbookFindFirstArgs} args - Arguments to find a Textbook
   * @example
   * // Get one Textbook
   * const textbook = await prisma.textbook.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TextbookFindFirstArgs>(args?: Prisma.SelectSubset<T, TextbookFindFirstArgs<ExtArgs>>): Prisma.Prisma__TextbookClient<runtime.Types.Result.GetResult<Prisma.$TextbookPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Textbook that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TextbookFindFirstOrThrowArgs} args - Arguments to find a Textbook
   * @example
   * // Get one Textbook
   * const textbook = await prisma.textbook.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TextbookFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TextbookFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TextbookClient<runtime.Types.Result.GetResult<Prisma.$TextbookPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Textbooks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TextbookFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Textbooks
   * const textbooks = await prisma.textbook.findMany()
   * 
   * // Get first 10 Textbooks
   * const textbooks = await prisma.textbook.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const textbookWithIdOnly = await prisma.textbook.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TextbookFindManyArgs>(args?: Prisma.SelectSubset<T, TextbookFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TextbookPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Textbook.
   * @param {TextbookCreateArgs} args - Arguments to create a Textbook.
   * @example
   * // Create one Textbook
   * const Textbook = await prisma.textbook.create({
   *   data: {
   *     // ... data to create a Textbook
   *   }
   * })
   * 
   */
  create<T extends TextbookCreateArgs>(args: Prisma.SelectSubset<T, TextbookCreateArgs<ExtArgs>>): Prisma.Prisma__TextbookClient<runtime.Types.Result.GetResult<Prisma.$TextbookPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Textbooks.
   * @param {TextbookCreateManyArgs} args - Arguments to create many Textbooks.
   * @example
   * // Create many Textbooks
   * const textbook = await prisma.textbook.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TextbookCreateManyArgs>(args?: Prisma.SelectSubset<T, TextbookCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Textbooks and returns the data saved in the database.
   * @param {TextbookCreateManyAndReturnArgs} args - Arguments to create many Textbooks.
   * @example
   * // Create many Textbooks
   * const textbook = await prisma.textbook.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Textbooks and only return the `id`
   * const textbookWithIdOnly = await prisma.textbook.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TextbookCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TextbookCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TextbookPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Textbook.
   * @param {TextbookDeleteArgs} args - Arguments to delete one Textbook.
   * @example
   * // Delete one Textbook
   * const Textbook = await prisma.textbook.delete({
   *   where: {
   *     // ... filter to delete one Textbook
   *   }
   * })
   * 
   */
  delete<T extends TextbookDeleteArgs>(args: Prisma.SelectSubset<T, TextbookDeleteArgs<ExtArgs>>): Prisma.Prisma__TextbookClient<runtime.Types.Result.GetResult<Prisma.$TextbookPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Textbook.
   * @param {TextbookUpdateArgs} args - Arguments to update one Textbook.
   * @example
   * // Update one Textbook
   * const textbook = await prisma.textbook.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TextbookUpdateArgs>(args: Prisma.SelectSubset<T, TextbookUpdateArgs<ExtArgs>>): Prisma.Prisma__TextbookClient<runtime.Types.Result.GetResult<Prisma.$TextbookPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Textbooks.
   * @param {TextbookDeleteManyArgs} args - Arguments to filter Textbooks to delete.
   * @example
   * // Delete a few Textbooks
   * const { count } = await prisma.textbook.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TextbookDeleteManyArgs>(args?: Prisma.SelectSubset<T, TextbookDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Textbooks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TextbookUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Textbooks
   * const textbook = await prisma.textbook.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TextbookUpdateManyArgs>(args: Prisma.SelectSubset<T, TextbookUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Textbooks and returns the data updated in the database.
   * @param {TextbookUpdateManyAndReturnArgs} args - Arguments to update many Textbooks.
   * @example
   * // Update many Textbooks
   * const textbook = await prisma.textbook.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Textbooks and only return the `id`
   * const textbookWithIdOnly = await prisma.textbook.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TextbookUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TextbookUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TextbookPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Textbook.
   * @param {TextbookUpsertArgs} args - Arguments to update or create a Textbook.
   * @example
   * // Update or create a Textbook
   * const textbook = await prisma.textbook.upsert({
   *   create: {
   *     // ... data to create a Textbook
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Textbook we want to update
   *   }
   * })
   */
  upsert<T extends TextbookUpsertArgs>(args: Prisma.SelectSubset<T, TextbookUpsertArgs<ExtArgs>>): Prisma.Prisma__TextbookClient<runtime.Types.Result.GetResult<Prisma.$TextbookPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Textbooks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TextbookCountArgs} args - Arguments to filter Textbooks to count.
   * @example
   * // Count the number of Textbooks
   * const count = await prisma.textbook.count({
   *   where: {
   *     // ... the filter for the Textbooks we want to count
   *   }
   * })
  **/
  count<T extends TextbookCountArgs>(
    args?: Prisma.Subset<T, TextbookCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TextbookCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Textbook.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TextbookAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TextbookAggregateArgs>(args: Prisma.Subset<T, TextbookAggregateArgs>): Prisma.PrismaPromise<GetTextbookAggregateType<T>>

  /**
   * Group by Textbook.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TextbookGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TextbookGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TextbookGroupByArgs['orderBy'] }
      : { orderBy?: TextbookGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TextbookGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTextbookGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Textbook model
 */
readonly fields: TextbookFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Textbook.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TextbookClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  sources<T extends Prisma.Textbook$sourcesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Textbook$sourcesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KnowledgeDocumentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  chapters<T extends Prisma.Textbook$chaptersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Textbook$chaptersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ChapterPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  author<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Textbook model
 */
export interface TextbookFieldRefs {
  readonly id: Prisma.FieldRef<"Textbook", 'String'>
  readonly title: Prisma.FieldRef<"Textbook", 'String'>
  readonly authorId: Prisma.FieldRef<"Textbook", 'String'>
  readonly description: Prisma.FieldRef<"Textbook", 'String'>
  readonly class: Prisma.FieldRef<"Textbook", 'String'>
  readonly uploadKey: Prisma.FieldRef<"Textbook", 'String'>
  readonly status: Prisma.FieldRef<"Textbook", 'TextbookStatus'>
  readonly createdAt: Prisma.FieldRef<"Textbook", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Textbook", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Textbook findUnique
 */
export type TextbookFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Textbook
   */
  select?: Prisma.TextbookSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Textbook
   */
  omit?: Prisma.TextbookOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TextbookInclude<ExtArgs> | null
  /**
   * Filter, which Textbook to fetch.
   */
  where: Prisma.TextbookWhereUniqueInput
}

/**
 * Textbook findUniqueOrThrow
 */
export type TextbookFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Textbook
   */
  select?: Prisma.TextbookSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Textbook
   */
  omit?: Prisma.TextbookOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TextbookInclude<ExtArgs> | null
  /**
   * Filter, which Textbook to fetch.
   */
  where: Prisma.TextbookWhereUniqueInput
}

/**
 * Textbook findFirst
 */
export type TextbookFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Textbook
   */
  select?: Prisma.TextbookSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Textbook
   */
  omit?: Prisma.TextbookOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TextbookInclude<ExtArgs> | null
  /**
   * Filter, which Textbook to fetch.
   */
  where?: Prisma.TextbookWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Textbooks to fetch.
   */
  orderBy?: Prisma.TextbookOrderByWithRelationInput | Prisma.TextbookOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Textbooks.
   */
  cursor?: Prisma.TextbookWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Textbooks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Textbooks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Textbooks.
   */
  distinct?: Prisma.TextbookScalarFieldEnum | Prisma.TextbookScalarFieldEnum[]
}

/**
 * Textbook findFirstOrThrow
 */
export type TextbookFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Textbook
   */
  select?: Prisma.TextbookSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Textbook
   */
  omit?: Prisma.TextbookOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TextbookInclude<ExtArgs> | null
  /**
   * Filter, which Textbook to fetch.
   */
  where?: Prisma.TextbookWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Textbooks to fetch.
   */
  orderBy?: Prisma.TextbookOrderByWithRelationInput | Prisma.TextbookOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Textbooks.
   */
  cursor?: Prisma.TextbookWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Textbooks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Textbooks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Textbooks.
   */
  distinct?: Prisma.TextbookScalarFieldEnum | Prisma.TextbookScalarFieldEnum[]
}

/**
 * Textbook findMany
 */
export type TextbookFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Textbook
   */
  select?: Prisma.TextbookSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Textbook
   */
  omit?: Prisma.TextbookOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TextbookInclude<ExtArgs> | null
  /**
   * Filter, which Textbooks to fetch.
   */
  where?: Prisma.TextbookWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Textbooks to fetch.
   */
  orderBy?: Prisma.TextbookOrderByWithRelationInput | Prisma.TextbookOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Textbooks.
   */
  cursor?: Prisma.TextbookWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Textbooks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Textbooks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Textbooks.
   */
  distinct?: Prisma.TextbookScalarFieldEnum | Prisma.TextbookScalarFieldEnum[]
}

/**
 * Textbook create
 */
export type TextbookCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Textbook
   */
  select?: Prisma.TextbookSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Textbook
   */
  omit?: Prisma.TextbookOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TextbookInclude<ExtArgs> | null
  /**
   * The data needed to create a Textbook.
   */
  data: Prisma.XOR<Prisma.TextbookCreateInput, Prisma.TextbookUncheckedCreateInput>
}

/**
 * Textbook createMany
 */
export type TextbookCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Textbooks.
   */
  data: Prisma.TextbookCreateManyInput | Prisma.TextbookCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Textbook createManyAndReturn
 */
export type TextbookCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Textbook
   */
  select?: Prisma.TextbookSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Textbook
   */
  omit?: Prisma.TextbookOmit<ExtArgs> | null
  /**
   * The data used to create many Textbooks.
   */
  data: Prisma.TextbookCreateManyInput | Prisma.TextbookCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TextbookIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Textbook update
 */
export type TextbookUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Textbook
   */
  select?: Prisma.TextbookSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Textbook
   */
  omit?: Prisma.TextbookOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TextbookInclude<ExtArgs> | null
  /**
   * The data needed to update a Textbook.
   */
  data: Prisma.XOR<Prisma.TextbookUpdateInput, Prisma.TextbookUncheckedUpdateInput>
  /**
   * Choose, which Textbook to update.
   */
  where: Prisma.TextbookWhereUniqueInput
}

/**
 * Textbook updateMany
 */
export type TextbookUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Textbooks.
   */
  data: Prisma.XOR<Prisma.TextbookUpdateManyMutationInput, Prisma.TextbookUncheckedUpdateManyInput>
  /**
   * Filter which Textbooks to update
   */
  where?: Prisma.TextbookWhereInput
  /**
   * Limit how many Textbooks to update.
   */
  limit?: number
}

/**
 * Textbook updateManyAndReturn
 */
export type TextbookUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Textbook
   */
  select?: Prisma.TextbookSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Textbook
   */
  omit?: Prisma.TextbookOmit<ExtArgs> | null
  /**
   * The data used to update Textbooks.
   */
  data: Prisma.XOR<Prisma.TextbookUpdateManyMutationInput, Prisma.TextbookUncheckedUpdateManyInput>
  /**
   * Filter which Textbooks to update
   */
  where?: Prisma.TextbookWhereInput
  /**
   * Limit how many Textbooks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TextbookIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Textbook upsert
 */
export type TextbookUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Textbook
   */
  select?: Prisma.TextbookSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Textbook
   */
  omit?: Prisma.TextbookOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TextbookInclude<ExtArgs> | null
  /**
   * The filter to search for the Textbook to update in case it exists.
   */
  where: Prisma.TextbookWhereUniqueInput
  /**
   * In case the Textbook found by the `where` argument doesn't exist, create a new Textbook with this data.
   */
  create: Prisma.XOR<Prisma.TextbookCreateInput, Prisma.TextbookUncheckedCreateInput>
  /**
   * In case the Textbook was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TextbookUpdateInput, Prisma.TextbookUncheckedUpdateInput>
}

/**
 * Textbook delete
 */
export type TextbookDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Textbook
   */
  select?: Prisma.TextbookSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Textbook
   */
  omit?: Prisma.TextbookOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TextbookInclude<ExtArgs> | null
  /**
   * Filter which Textbook to delete.
   */
  where: Prisma.TextbookWhereUniqueInput
}

/**
 * Textbook deleteMany
 */
export type TextbookDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Textbooks to delete
   */
  where?: Prisma.TextbookWhereInput
  /**
   * Limit how many Textbooks to delete.
   */
  limit?: number
}

/**
 * Textbook.sources
 */
export type Textbook$sourcesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KnowledgeDocument
   */
  select?: Prisma.KnowledgeDocumentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KnowledgeDocument
   */
  omit?: Prisma.KnowledgeDocumentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KnowledgeDocumentInclude<ExtArgs> | null
  where?: Prisma.KnowledgeDocumentWhereInput
  orderBy?: Prisma.KnowledgeDocumentOrderByWithRelationInput | Prisma.KnowledgeDocumentOrderByWithRelationInput[]
  cursor?: Prisma.KnowledgeDocumentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.KnowledgeDocumentScalarFieldEnum | Prisma.KnowledgeDocumentScalarFieldEnum[]
}

/**
 * Textbook.chapters
 */
export type Textbook$chaptersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Chapter
   */
  select?: Prisma.ChapterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Chapter
   */
  omit?: Prisma.ChapterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChapterInclude<ExtArgs> | null
  where?: Prisma.ChapterWhereInput
  orderBy?: Prisma.ChapterOrderByWithRelationInput | Prisma.ChapterOrderByWithRelationInput[]
  cursor?: Prisma.ChapterWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ChapterScalarFieldEnum | Prisma.ChapterScalarFieldEnum[]
}

/**
 * Textbook without action
 */
export type TextbookDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Textbook
   */
  select?: Prisma.TextbookSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Textbook
   */
  omit?: Prisma.TextbookOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TextbookInclude<ExtArgs> | null
}
